package javaBeans;
// Generated Dec 23, 2020 9:01:02 AM by Hibernate Tools 5.1.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Invoicedetail generated by hbm2java
 */
@Entity
@Table(name = "invoicedetail", catalog = "minishop")
public class Invoicedetail implements java.io.Serializable {

	private InvoicedetailId id;

	public Invoicedetail() {
	}

	public Invoicedetail(InvoicedetailId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "InvoiceId", nullable = false, length = 32)),
			@AttributeOverride(name = "productId", column = @Column(name = "ProductId", nullable = false)),
			@AttributeOverride(name = "quantity", column = @Column(name = "Quantity", nullable = false)),
			@AttributeOverride(name = "price", column = @Column(name = "Price", nullable = false)) })
	public InvoicedetailId getId() {
		return this.id;
	}

	public void setId(InvoicedetailId id) {
		this.id = id;
	}

}
